cluster.name: doc-search-es-cluster
node.name: node-1
node.roles: [ master,data ]
cluster.initial_master_nodes: [ "node-1" ]
bootstrap.memory_lock: true
network.host: 0.0.0.0
http.host: 0.0.0.0
http.port: 9200
discovery.seed_hosts: [ "node-1" ]

xpack.security.enabled: false
xpack.security.enrollment.enabled: false
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false

ingest.geoip.downloader.enabled: false
