server:
  port: 80
  servlet:
    context-path: /

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: doc-search
      gridfs:
        database: doc-search
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.joe.doc.controller

knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表